--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "HR"."ORDERS" 
   (	"ROWIDS" NUMBER, 
	"ORDERID" VARCHAR2(2000), 
	"ORDERDATE" DATE, 
	"SHIPDATE" DATE, 
	"SHIPMODE" VARCHAR2(2000), 
	"CUSTOMERID" VARCHAR2(2000), 
	"CUSTOMERNAME" VARCHAR2(2000), 
	"SEGMENT" VARCHAR2(2000), 
	"COUNTRYREGION" VARCHAR2(2000), 
	"CITY" VARCHAR2(2000), 
	"STATE" VARCHAR2(2000), 
	"POSTALCODE" VARCHAR2(2000), 
	"REGION" VARCHAR2(2000), 
	"PRODUCTID" VARCHAR2(2000), 
	"CATEGORY" VARCHAR2(2000), 
	"SUBCATEGORY" VARCHAR2(2000), 
	"PRODUCTNAME" VARCHAR2(2000), 
	"SALES" NUMBER, 
	"QUANTITY" NUMBER, 
	"DISCOUNT" NUMBER, 
	"PROFIT" NUMBER
   ) ;